redis:
        image: redis:alpine
        volumes:
        - ${PWD}/tmp/data:/data
        ports:
        - "6379"

mosquitto:
        build: .
        volumes:
        - ${PWD}/auth-plugin.conf:/etc/mosquitto.d/auth-plugin.conf
        ports:
        - "1883:1883"
        - "9883:9883"
        environment:
        - DOMAIN=example.com
        - PORT=8080
        links:
        - redis:mosquitto.redis.link

